---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "tekton.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tekton.serviceAccountName" . }}-controller
    namespace: {{ include "tekton.namespace" . }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-webhook
  labels:
    app.kubernetes.io/component: webhook
  {{- include "tekton.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tekton.serviceAccountName" . }}-webhook
    namespace: {{ include "tekton.namespace" . }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-webhook
  apiGroup: rbac.authorization.k8s.io