---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton.serviceAccountName" . }}-controller
  labels:
    app.kubernetes.io/component: controller
    {{- include "tekton.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton.serviceAccountName" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
    {{- include "tekton.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
