{{- if .Values.basicauth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redisinsight.fullname" . }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth: |
{{- range .Values.basicauth.credentials }}
    {{ htpasswd .username .password }}
{{- end }}
{{- end }}
