apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ci-status.fullname" . }}
  labels:
    {{- include "ci-status.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl .Values.config . | b64enc | quote }}
