{{- $labels := (include "app.labels" .) }}
{{- $fullname := (include "app.fullname" .) }}
{{- range .Values.configs }}
{{- $name := .name | lower | replace "_" "-" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- $labels | nindent 4 }}
  name: {{ printf "%s-%s" $fullname $name }}
data:
  {{- if eq (default "enabled" .subPath) "enabled" }}
  {{ .key }}: {{ toYaml .value | indent 2 }}
  {{- else }}
  {{- toYaml .value | nindent 2 }}
  {{- end }}
{{- end }}
