{{- range .Values.configs }}
{{- $name := .name | lower | replace "_" "-" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ printf "%s-%s" (include "app.fullname" .) $name }}
data:
{{- range .Values.configs }}
  {{ .key }}: {{ toYaml .value | indent 2 }}
{{- end }}
{{- end }}
