{{- if .Values.networkPolicies }}
{{- range .Values.networkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- if $.Values.annotations }}
  annotations:
  {{ toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ template "app.fullname" . }}-{{ .name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}
  policyTypes:
    {{- toYaml .types | nindent 4 }}
  {{- if .ingress }}
  ingress:
    {{- toYaml .ingress | nindent 4 }}
  {{- end }}
  {{- if .egress }}
  egress:
    {{- toYaml .egress | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
