{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ template "app.fullname" . }}
type: Opaque
data:
{{- range .Values.secrets }}
  {{ .key }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
