---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  labels:
    app.kubernetes.io/component: webhook
    {{- include "tekton.labels" . | nindent 4 }}
    pipeline.tekton.dev/release: {{ include "tekton.version" . }}
